var NutritionNDB = new mongoose.Schema({
    "sku": {type: String, unique: true},
    "ndb_url": Number,
    "ndb_id": Number,
    "name": String,
    "unit": Number,
    "unit_type": String,
    "eq_gram": Number,
    "ingredients": [String],
    
    "Protein": String,
    "Total lipid (fat)": String,
    "Carbohydrate, by difference": String,
    "Ash": String,
    "Energy": String,
    "Starch": String,
    "Sucrose": String,
    "Glucose (dextrose)": String,
    "Fructose": String,
    "Lactose": String,
    "Maltose": String,
    "Alcohol, ethyl": String,
    "Water": String,
    "Caffeine": String,
    "Theobromine": String,
    "Sugars, total": String,
    "Galactose": String,
    "Fiber, total dietary": String,
    "Calcium, Ca": String,
    "Iron, Fe": String,
    "Magnesium, Mg": String,
    "Phosphorus, P": String,
    "Potassium, K": String,
    "Sodium, Na": String,
    "Zinc, Zn": String,
    "Copper, Cu": String,
    "Fluoride, F": String,
    "Manganese, Mn": String,
    "Selenium, Se": String,
    "Vitamin A, IU": String,
    "Retinol": String,
    "Vitamin A, RAE": String,
    "Carotene, beta": String,
    "Carotene, alpha": String,
    "Vitamin E (alpha-tocopherol": String,
    "Vitamin D": String,
    "Vitamin D2 (ergocalciferol": String,
    "Vitamin D3 (cholecalciferol": String,
    "Vitamin D (D2 + D3": String,
    "Cryptoxanthin, beta": String,
    "Lycopene": String,
    "ZEA~^~Lutein + zeaxanthin": String,
    "Tocopherol, beta": String,
    "Tocopherol, gamma": String,
    "Tocopherol, delta": String,
    "Tocotrienol, alpha": String,
    "Tocotrienol, beta": String,
    "Tocotrienol, gamma": String,
    "Tocotrienol, delta": String,
    "Vitamin C, total ascorbic acid": String,
    "Thiamin": String,
    "Riboflavin": String,
    "Niacin": String,
    "Pantothenic acid": String,
    "Vitamin B-6": String,
    "Folate, total": String,
    "Vitamin B-12": String,
    "Choline, total": String,
    "Menaquinone-4": String,
    "Dihydrophylloquinone": String,
    "Vitamin K (phylloquinone": String,
    "Folic acid": String,
    "Folate, food": String,
    "Folate, DFE": String,
    "Betaine": String,
    "Tryptophan": String,
    "Threonine": String,
    "Isoleucine": String,
    "Leucine": String,
    "Lysine": String,
    "Methionine": String,
    "Cystine": String,
    "Phenylalanine": String,
    "Tyrosine": String,
    "Valine": String,
    "Arginine": String,
    "Histidine": String,
    "Alanine": String,
    "Aspartic acid": String,
    "Glutamic acid": String,
    "Glycine": String,
    "Proline": String,
    "Serine": String,
    "Hydroxyproline": String,
    "Cholesterol": String,
    "Fatty acids, total trans": String,
    "Fatty acids, total saturated": String,
    "Phytosterols": String,
    "Stigmasterol": String,
    "Campesterol": String,
    "Beta-sitosterol": String,
    "Fatty acids, total monounsaturated": String,
    "Fatty acids, total polyunsaturated": String,
    "Fatty acids, total trans-monoenoic": String,
    "Fatty acids, total trans-polyenoic": String,
});

module.exports = mongoose.model('NutritionNDB', NutritionNDB);
